# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-10 09:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rtwtheme', '0003_auto_20161201_1706'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HomePage',
            new_name='LandingPage',
        ),
        migrations.RenameField(
            model_name='slide',
            old_name='homepage',
            new_name='landingpage',
        ),
    ]
