# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-10 09:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rtwtheme', '0004_auto_20161210_0902'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LandingPage',
            new_name='HomePage',
        ),
        migrations.RenameField(
            model_name='slide',
            old_name='landingpage',
            new_name='homepage',
        ),
    ]
