# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-11 20:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0002_auto_20141227_0224'),
        ('pages', '0003_auto_20150527_1555'),
        ('rtwtheme', '0005_auto_20161210_0954'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardPage',
            fields=[
                ('gallery_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='galleries.Gallery')),
                ('videolink', models.URLField(blank=True, help_text='A link for youtube videos')),
            ],
            options={
                'verbose_name': 'Cardpage',
                'ordering': ('_order',),
                'verbose_name_plural': 'Cardpages',
            },
            bases=('galleries.gallery',),
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='page_ptr',
        ),
        migrations.AlterField(
            model_name='homepage',
            name='buttontext',
            field=models.CharField(blank=True, help_text='The text on the button to enter the page', max_length=200),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='headline',
            field=models.CharField(blank=True, help_text='The Headline in the middle of the carousel caption', max_length=200),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='subheading',
            field=models.CharField(blank=True, default='Default', help_text='The subheading of the carousel caption', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='homepage',
            name='topheading',
            field=models.CharField(blank=True, help_text='The top heading of the carousel caption', max_length=200),
        ),
        migrations.DeleteModel(
            name='Portfolio',
        ),
    ]
