# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-01 09:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0003_gallery_url'),
        ('pages', '0003_auto_20150527_1555'),
        ('rtwtheme', '0006_auto_20161211_2029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardpage',
            name='gallery_ptr',
        ),
        migrations.DeleteModel(
            name='CardPage',
        ),
    ]
