# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-11 20:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20150527_1555'),
        ('rtwtheme', '0006_auto_20161211_2029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardpage',
            name='gallery_ptr',
        ),
        migrations.AddField(
            model_name='cardpage',
            name='page_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.Page'),
            preserve_default=False,
        ),
    ]
