# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-01 13:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0004_remove_gallery_url'),
        ('rtwtheme', '0007_auto_20170101_0917'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_order', mezzanine.core.fields.OrderField(null=True, verbose_name='Order')),
                ('video_url', models.URLField(blank=True, verbose_name='Video')),
                ('title', models.CharField(default='Video', max_length=50)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='galleries.Gallery')),
            ],
            options={
                'ordering': ('_order',),
            },
        ),
    ]
